apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-public-api
  namespace: sc-public-api
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-balanced
  fstype: ext4
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-public-api
  namespace: public

spec:
  storageClassName: sc-public-api
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
