apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: public-stage

# deprecated
commonLabels:
  app: public-api
  team: devops

# labels:
# - pairs:
#     app: public-api
#     team: devops
#   includeSelectors: true

commonAnnotations:
  note: "This is an STAGE deployment"

resources:
  - ns.yaml
  - ../../base

# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patchesstrategicmerge/
patchesStrategicMerge:
  - deploy-strategic-patch.yaml

# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/
# https://fabianlee.org/2022/04/15/kubernetes-kustomize-transformations-with-patchesjson6902/
patches:
# yaml file patch
  - target:
      kind: ConfigMap
      name: cm-private-api
    path: cm-patch.yaml

  - target:
      kind: Ingress
      name: public-api
    path: ing-patch.yaml

  # In-line patch
  - target:
      kind: Service
      name: public-api
    patch: |-
      - op: add
        path: /spec/type
        value: ClusterIP



# Image patch
images:
  - name: KUSTOMIZE-DEFINED
    newName: <DOCKER REPO>/kubelabs_publicapi
    newTag: 1.0.0  # <- cambiar la version correcta.

