# issuer-lets-encrypt-staging.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: public-stage
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: carlos.echc11@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          name: public-api
