apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: public

commonLabels:
  app: public-api
  team: devops

resources:
  - ns.yaml
  - ../../base

patches:
  - target:
      kind: Deployment
      name: public-api
    path: deploy-patch.yaml
  - target:
      kind: ConfigMap
      name: cm-private-api
    path: cm-patch.yaml
  - target:
      kind: Ingress
      name: public-api
    path: ing-patch.yaml
  - target:
      kind: PersistentVolume
      name: filestore-nfs-pv
    path: pv-patch.yaml
  - target:
      kind: PersistentVolumeClaim
      name: fs-storage
    path: pv-patch.yaml

# Image patch
images:
  - name: KUSTOMIZE-DEFINED
    newName: cachac/kubelabs_publicapi_test
    newTag: 1.0.1

