apiVersion: v1
kind: PersistentVolume
metadata:
  name: filestore-nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /volumes           # CHANGE PATH
    server: 10.19.174.138    # CHANGE SERVER IP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filestore-nfs-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: filestore-nfs-pv
  resources:
    requests:
      storage: 1Gi
