apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # storage
  - storage.yaml
  # config
  - cm.yml
  - secret.yaml
  # networking
  - issuer.yaml
  - svc.yml
  - ing.yml
  # workload
  - deploy.yml
